# Generated by Django 4.0.4 on 2022-04-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
